import './global.css';
import ThemeProvider from './styles/theme/ThemeProvider';

export const metadata = {
  title: 'Welcome to gearframe',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
